// Generated by CoffeeScript 1.6.3
'use strict';
var DISPEAK_KEYGEN;

DISPEAK_KEYGEN = (function() {
  var BITS;

  function DISPEAK_KEYGEN() {}

  BITS = 2048;

  DISPEAK_KEYGEN.prototype.GeneratePrivateKey = function() {
    return cryptico.generateRSAKey("", BITS);
  };

  DISPEAK_KEYGEN.prototype.GeneratePublicKey = function(priaveteKey) {
    return cryptico.publicKeyString(priaveteKey);
  };

  DISPEAK_KEYGEN.prototype.EncryptMsg = function(publicKey, msg) {
    return cryptico.encrypt(msg, publicKey);
  };

  DISPEAK_KEYGEN.prototype.DecryptMsg = function(priavetKey, msg) {
    return cryptico.decrypt(msg, priavetKey);
  };

  return DISPEAK_KEYGEN;

})();
