// Generated by CoffeeScript 1.6.3
"use strict";
module.exports = function(settings, nconf, libs) {
  var RSA, RSA_INTERFACE, app;
  app = libs.app;
  RSA_INTERFACE = require('./RSA');
  RSA = new RSA_INTERFACE();
  app.get('/keys', function(req, res) {
    return RSA.create(function(ret) {
      return res.send(ret);
    });
  });
  return this;
};
