// Generated by CoffeeScript 1.6.3
"use strict";
var RSA;

RSA = (function() {
  function RSA() {
    this.rsa = require('rsa-json');
  }

  RSA.prototype.create = function(next) {
    return this.rsa({
      bits: 2048
    }, function(err, pair) {
      if (err) {
        next('error');
      }
      pair["public"] = pair["public"].replace(/\n/gm, "");
      pair["private"] = pair["private"].replace(/\n/gm, "");
      return next(pair);
    });
  };

  return RSA;

})();

module.exports = RSA;
